### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by 4yush** [DSMorpher/Dota2-Invoker-Keys#1] opened 2017-11-04 15:25 UTC
I really liked this script although it stopped working after the 7.07 patch. Can it be fixed?

**Comment by Umer-Javaid** [comment] 2017-11-04 16:28
@4yush The script is working fine. I tried to reproduce the issue as follows
 * I verified using the binaries shipped along with the script. 
 * I also re-built the script and used the fresh binaries. 

Both are working fine.... 
Kindly provide more details on how to reproduce this issue.

**Comment by 4yush** [comment] 2017-11-05 13:25
Try Using it in game. It works outside the game but in game it doesn't
work.

**Comment by Umer-Javaid** [comment] 2017-11-05 17:50
The keys are working in the "demo-hero" section of the game. Can you verify if it works there? and also if possible build the script on your local machine. Let me know the results.

**Comment by 4yush** [comment] 2017-11-05 17:57
I tried but its not working.. It used to work great.. But I don't
understand what the problem is.. Anyways thank you for helping..

**Comment by dheshanm** [comment] 2017-11-08 07:06
Just tried it works Fine. Can you check if the keys are being pressed by executing one of the combo keys with the chat turned on?

**Comment by 4yush** [comment] 2017-11-08 07:13
It's working in chat. But when chat is closed only the first key is getting
pressed. Suppose i press alt + t for sunstrike only one exort or gets
triggered.

**Comment by Umer-Javaid** [comment] 2017-11-09 16:48
@4yush It is working for me and @L4TTiCe as well. Even in your own case it executes the combos in the chat as u said. I am un-able to figure out the root cause. 
This is a machine-specific issue and It might be fixed after you install [auto-hotkey](https://autohotkey.com/) on your system and then compile the script locally. Kindly let me know the outcome.

**Comment by Venryx** [comment] 2018-05-18 09:10
I'm getting the same issue: In the chat window, it always adds "eeer", but when playing (or in hero-demo), it sometimes only "counts" one or two of the "e" presses instead of all three, meaning that the resulting spell invoked is wrong.

I've tried it with the exe and the ahk script file with the same results.

**Comment by Umer-Javaid** [comment] 2018-05-20 17:46
I have provided a possible fix for your issue. Kindly re-compile the script on your machine or use the updated binaries provided. Also kindly let me know if the issue is solved or not as I am unable to reproduce it on my machine.

**Comment by Venryx** [comment] 2018-05-20 22:29
I've tested the new version, and it does improve the reliability for the Alt+T combo. Instead of working 80% of the time, it now works about 95% of the time. Which is probably good enough.

Since merging the key-presses into a single "Send" command seems to improve the reliability, we could take it a step further and combine all of the key-presses into one command -- not just the presses of the main key.

Like this:
```
;DOTA 2 SCRIPT

#NoEnv
SendMode Input
SetWorkingDir %A_ScriptDir%
#InstallKeybdHook
#UseHook
#KeyHistory 0
#SingleInstance force
#MaxHotKeysPerInterval 10000

#If Winactive("ahk_class Valve001") || Winactive("ahk_class SDL_app")
{
	WheelUp::
		Send {PgUp}
	return
	WheelDown::
		Send {PgDn}
	return
	
	;Invoker Tool Keys
		;Sun strike
			LAlt & t::
				Send {e 3}{r}
			return
		;Chaos Meteor
			LAlt & d::
				Send {e 2}{w}{r}
			return
		;Forge Spirit
			LAlt & f::
				Send {e 2}{q}{r}
			return
		;Cold Snap
			LAlt & y::
				Send {q 3}{r}
			return
		;Ghost Walk
			LAlt & v::
				Send {q 2}{w}{r}
			return
		;Ice Wall
			LAlt & g::
				Send {q 2}{e}{r}
			return
		;Alacrity
			LAlt & z::
				Send {w 2}{e}{r}
			return
		;Tornado
			LAlt & x::
				Send {w 2}{q}{r}
			return
		;EMP
			LAlt & c::
				Send {w 3}{r}
			return
		;Deafening Blast
			LAlt & b::
				Send {q}{w}{e}{r}
			return
}
```

It works for me, and improves the reliability of the combos.

I tested just now, and it had 25 successes in a row before finally having a key "dropped" in one of the combos, so about a 95% success rate with the above code.

**Comment by Umer-Javaid** [comment] 2018-05-27 07:52
@4yush , @Venryx  I have provided a fix for your issue. Kindly re-compile the script on your machine or use the updated binaries provided.
The issue was being caused by 

1. 7.07-7.12 Update as the "Alt" key has a special meaning in the game.
2. Turning off the "num-lock" key on certain keyboards makes the script go crazy.

Therefore closing the issue now.

**Comment by Umer-Javaid** [comment] 2018-05-27 07:53
@4yush , @Venryx I have provided a fix for your issue. Kindly re-compile the script on your machine or use the updated binaries provided.
The issue was being caused by

7.07-7.12 Update as the "Alt" key has a special meaning in the game.
Turning off the "num-lock" key on certain keyboards makes the script go crazy.
Therefore closing the issue now.

**Closed as completed by Umer-Javaid** 2018-05-27 07:53 UTC
Labels: question

**Comment by Umer-Javaid** [comment] 2018-05-27 07:54
@4yush , @Venryx I have provided a fix for your issue. Kindly re-compile the script on your machine or use the updated binaries provided.
The issue was being caused by

1. 7.07-7.12 Update as the "Alt" key has a special meaning in the game.
2. Turning off the "num-lock" key on certain keyboards makes the script go crazy.

Therefore closing the issue now.
